# Generated by Django 5.2 on 2025-08-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_is_rescue'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='operational_area',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
