# Generated by Django 5.2.5 on 2025-08-15 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
        ('users', '0002_post_is_rescue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ani_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.post')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_rescues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
