# Generated by Django 5.2.5 on 2025-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_rescue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
